### ISSUE TITLE
Automatic file tests

### ISSUE THREAD

**Issue by Idrinth** [IDotD/Raid-Tiers#4]
@Theodotosp would it help you if files would automatically be tested once you changed them, so you have direct feedback if they are correct or not?

Could setup https://github.com/Idrinth/config-check to test that, you'd just need to move to merging to see that even earlier.

**Comment by Theodotosp** [comment]
ok,this seems interesting. I will have a closer look when you are done :)

**Comment by Idrinth** [comment]
https://travis-ci.org/IDotD/Raid-Tiers is setup for now, it's obviously not complete yet, but it already checks the files.

**Comment by Idrinth** [comment]
I think this is pretty much done.
